### PR TITLE
Fix out of process websocket check

### LINKED ISSUE #815: WebSocket test regression
http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=1201716353821780817&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50

This test started failing yesterday on Win7 & 2008 R2. It looks like some OS detection regressed.

```
======= Failed test run #1 ==========
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Disabled
Actual:   Enabled
          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.UpgradeFeatureDetectionTests.UpgradeFeatureDetectionDeployer(RuntimeFlavor runtimeFlavor, ApplicationType applicationType, String configPath, String sitePath, String expected) in /_/test/IISIntegration.FunctionalTests/UpgradeFeatureDetectionTests.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-05-04T00:24:33] TestLifetime Information: Starting test UpgradeFeatureDetectionDisabled_OutOfProcess_IISExpress_CoreClr_x64_Portable
| [2018-05-04T00:24:33] TestLifetime Information: Starting test HelloWorld_CoreClr
| [2018-05-04T00:24:33] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [2018-05-04T00:24:33] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=UpgradeFeatureDetection
| [2018-05-04T00:24:33] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\f39e34b5-95dc-438c-885e-f01473f7a868" --framework netcoreapp2.1 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [2018-05-04T00:24:33] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
| [2018-05-04T00:24:33] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2018-05-04T00:24:34] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   TestTasks -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.1\TestTasks.dll
| [2018-05-04T00:24:34] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IISIntegration -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration\bin\Release\netstandard2.0\Microsoft.AspNetCore.Server.IISIntegration.dll
| [2018-05-04T00:24:34] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   OutOfProcessWebSite -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\WebSites\OutOfProcessWebSite\bin\Release\netcoreapp2.1\OutOfProcessWebSite.dll
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   OutOfProcessWebSite -> C:\BuildAgent\temp\buildTmp\f39e34b5-95dc-438c-885e-f01473f7a868\
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to start IIS Express on port: 56606
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\BuildAgent\temp\buildTmp\tmp547A.tmp /trace:error
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=UpgradeFeatureDetection
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 13892 started
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 1437095109 
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 1437095125 
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 1437095125 
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1437095125 
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:56606/" for site "HttpTestSite" application "/"
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 13892, Port: 56606
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Application ready at URL: http://localhost:56606/
| [2018-05-04T00:24:35] HelloWorldTest Warning: Retry count 1..
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [2018-05-04T00:24:35] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:56606/UpgradeFeatureDetection
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:56606/UpgradeFeatureDetection with HTTP status 200.0
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:56606/UpgradeFeatureDetection with HTTP status 200.0
| [2018-05-04T00:24:36] HelloWorldTest Warning: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                               {
|                                                 Transfer-Encoding: chunked
|                                                 Server: Kestrel
|                                                 X-SourceFiles: =?UTF-8?B?QzpcQnVpbGRBZ2VudFx0ZW1wXGJ1aWxkVG1wXGYzOWUzNGI1LTk1ZGMtNDM4Yy04ODVlLWYwMTQ3M2Y3YTg2OFxVcGdyYWRlRmVhdHVyZURldGVjdGlvbg==?=
|                                                 X-Powered-By: ASP.NET
|                                                 Date: Fri, 04 May 2018 07:24:36 GMT
|                                               }
| [2018-05-04T00:24:36] HelloWorldTest Warning: Enabled
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to cancel process 13892
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 13892 shut down
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Host process shutting down.
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Successfully terminated host process with process Id '13892'
| [2018-05-04T00:24:36] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: [Time]: Total time taken for this test variation '3.4167474' seconds
| [2018-05-04T00:24:36] TestLifetime Information: Finished test HelloWorld_CoreClr in 3.4177104s
```

cc @ryanbrandenburg

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes #815 . Checking if the websocket module in the apphost.config file isn't sufficient for know if the websocket module is installed. Therefore, we also need to check if the WEBSOCKET_VERSION server variable is set (same check that is used for inprocess).

### CODE REVIEW

**Comment by jkotalik** [comment]
Verified on a private Win7 VM this works.

**Comment by pakrym** [comment]
Why didn't this work https://github.com/aspnet/IISIntegration/blob/6629236a0e72b143a36d552ab314282d9d2bb60f/src/Microsoft.AspNetCore.Server.IISIntegration/Server/IISHttpServer.cs#L44?

**Comment by Tratcher** [comment]
How did it regress?

**Comment by jkotalik** [comment]
The check you linked above is for inprocess. The test is failing for out of process.

**Comment by jkotalik** [comment]
I don't believe it regressed, I think the test I had before was incorrect due to the wrong site path, which means it ran the inprocess test twice. See: calendar.google.com/calendar/r/settings/calendar/Y3Y1b2NqZHFkZjRiMmxsbGo2N3Z0dnVzYjBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

File: src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx [hunk 1]
```diff
@@ -347,6 +347,19 @@ ASPNETCORE_CONFIG::Populate(
         }
     }
 
+    if (m_fWebSocketEnabled)
```
Comment (pakrym) [inline src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: Do we need the code before this?

Comment (jkotalik) [reply src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: I'd prefer too. If the websocket module is disabled in the applicationhost.config, it would be ignored by removing the prior check.

Comment (pan-wang) [reply src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: how could this happen? if websocket module was enabled while WEBSOCKET_VERSION was not set, it means Websocket failed ealrier. The websocket request should not be reached ANCM at all due to failure earlier

Comment (pakrym) [reply src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: Isn't websocket module the one setting variable? If it's disabled nothing would be set in theory.

Comment (pan-wang) [reply src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: I now have more context about this one. This looks as a bad design of IIS websocket module and setup. I think we can just check server variable WEBSOCKET_VERSION as Websocket module always sets it and ignore configuration.

File: src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx [hunk 2]
```diff
@@ -322,29 +320,18 @@ ASPNETCORE_CONFIG::Populate(
...
-
-    hr = pAdminManager->GetAdminSection(bstrWebsocketSection,
-        m_struConfigPath.QueryStr(),
-        &pWebSocketElement);
+    // Even though the applicationhost.config file contains the websocket element,
+    // the websocket module may still not be enabled. Check if the
+    PCWSTR pszVariableValue;
+    DWORD cbLength;
+    hr = pHttpContext->GetServerVariable("WEBSOCKET_VERSION", &pszVariableValue, &cbLength);
     if (FAILED(hr))
```
Comment (pakrym) [inline src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: `m_fWebSocketEnabled = !FAILED(hr)`

Comment (jkotalik) [reply src/AspNetCoreModuleV2/CommonLib/aspnetcoreconfig.cxx]: oops I meant to fix that. I'll merge that to dev.
